#  弹幕保存路径 只作用于CLI模式
save-path: ""
# dandan api模式
# real_time 实时
# database sqlite数据库
dandan-mode: "real_time"
dandan-timeout: 60 # dandan api timeout in seconds
ua: "" # 请求ua 可不配置
# 分词器配置 用于提升识别准确率
tokenizer:
  # 是否启用
  enable: true
  # 搜索结果标题黑名单 regex正则匹配搜索结果标题 replacement 则是需要替换为的词 提升匹配精准度
  # 注意 \ 转义
  blacklist:
    - regex: "(刺客)*伍六七.*记忆碎片"
      replacement: "刺客伍六七第五季"
    - regex: "(刺客)*伍六七.*暗影宿命"
      replacement: "刺客伍六七第四季"
    - regex: "(刺客)*伍六七.*玄武国篇"
      replacement: "刺客伍六七第三季"
    - regex: "(刺客)*伍六七.*最强发型师"
      replacement: "刺客伍六七第二季"
    - regex: "(刺客)*伍六七"
      replacement: "刺客伍六七"
    - regex: "仙剑奇侠传\\s*第*\\s*(一|1)\\s*部*"
      replacement: "仙剑奇侠传"
server:
#  dandan api token 配置
  tokens:
    - "xxx"
    - "aaa"
  timeout: 10
  port: 8089
#  emby 配置，用于更加精准的搜索。注意token权限，系统使用用户API进行搜索，不要给管理员TOKEN
emby:
  url: ""
  user: ""
  token: ""
#  目前可选 bilibili tencent youku iqiyi 配置均通用
platforms:
  - name: "bilibili"
  #  优先级 用于控制剧集搜索结果 越小则排的更靠前(int) <0 则禁用该平台
    priority: 10
  #  完整cookie 否则部分接口不出数据
    cookie: ""
  #  单个视频弹幕下载的并发数 调高了注意账号风险 用的b站6min一段的弹幕接口，调高了意义也不大
    max-worker: 4 # 默认4
  #  请求超时时间 单位：秒
    timeout: 10
    # 合并毫秒内重复弹幕 单位 ms <=0则不启用 同时作用于弹幕抓取和dandan api
    merge-danmaku-in-mills: 1000
    # 弹幕保存文件类型 xml 或者 ass
    persists: ["xml", "ass"]
  - name: "tencent"
    priority: 100
    cookie: "xxx" # 最好提供，否则可能会导致搜不到数据
    max-worker: 8 # 默认 8
    timeout: 100
    merge-danmaku-in-mills: 1000
    persists: ["xml", "ass"]